---
abstract: 'faster version of Net::Async::Redis'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Deep: '0'
  Test::Fatal: '0.016'
  Test::HexString: '0'
  Test::MemoryGrowth: '0'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-Redis-XS
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Net::Async::Redis::Cluster::Node::XS:
    file: lib/Net/Async/Redis/Cluster/Node/XS.pm
    version: '0.013'
  Net::Async::Redis::Cluster::XS:
    file: lib/Net/Async/Redis/Cluster/XS.pm
    version: '0.013'
  Net::Async::Redis::Protocol::XS:
    file: lib/Net/Async/Redis/XS.pm
    version: '0.013'
  Net::Async::Redis::XS:
    file: lib/Net/Async/Redis/XS.pm
    version: '0.013'
requires:
  Future::AsyncAwait: '0.61'
  IO::Async::Loop: '0'
  Net::Async::Redis: '4.002'
  perl: '5.026'
resources:
  bugtracker: https://github.com/team-at-cpan/Net-Async-Redis-XS/issues
  homepage: https://github.com/team-at-cpan/Net-Async-Redis-XS
  repository: https://github.com/team-at-cpan/Net-Async-Redis-XS.git
version: '0.013'
x_authority: cpan:TEAM
x_contributors:
  - 'Tom Molesworth <tom@deriv.com>'
  - 'Gabor Szabo <gabor@szabgab.com>'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
